version: "3"
services:
  app:
    image: stock-retriever:1.0.0
    container_name: stock_retriever_container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: