spring:
  application:
    name: stocksRetriever
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    database: postgresql
  liquibase:
    enabled: false
logging:
  level:
    root: debug
client:
  timespan: day
  multiplier: 1
  apiKey: Dup9fAGhFrqYXFIe_YBPP6GrlFtvYjFK